---
title: "Case 1 Extra Credit"
author: "Ryan Hastings"
date: "2/24/2021"
output: pdf_document
header-includes: 
  - \usepackage{lscape}
---

I was able to reproduce most of the values in Table 1. However, some are off by 
a tenth of a percent or so. This is likely based on how missing values are dealt 
with. It is unclear whether the authors drop missing values from the denominator 
when calculating proportions.


I was able to reproduce all the values in Table 4 perfectly.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
require(tidyverse)
require(stargazer)
require(survival)
require(survminer)
```

```{r}
dig <- read_csv("dig.csv") %>% 
  janitor::clean_names()
```

```{r tab1, results = 'asis'}
tab1 <- dig %>% 
  group_by(trtmt) %>% 
  summarize(
    "N" = n(),
    "Age (yr) - mean" = mean(age),
    "Age (yr) - SD" = sd(age),
    "Ejection fraction - mean" = mean(ejf_per),
    "Ejection fraction - SD" = sd(ejf_per),
    "Median duration of CHF - mo" = median(chfdur, na.rm =T),
    "Female Sex" = sum(sex == 2)/n() * 100,
    "Nonwhite Race" = sum(race == 2)/n() * 100,
    "Age >70 yr" = sum(age > 70)/n() * 100,
    "Method - ventriculography" = sum(ejfmeth == 1)/n() * 100,
    "Method - echocardiography" = sum(ejfmeth == 3)/n() * 100,
    "Method - angiography" = sum(ejfmeth == 2)/n() * 100,
    "Cardiothoracic ratio >0.55" = sum(chestx > 0.55, na.rm =T)/n() * 100,
    "NYHA class - I" = sum(functcls == 1, na.rm =T)/n() * 100,
    "NYHA class - II" = sum(functcls == 2, na.rm =T)/n() * 100,
    "NYHA class - III" = sum(functcls == 3, na.rm =T)/n() * 100,
    "NYHA class - IV" = sum(functcls == 4, na.rm =T)/n() * 100,
    "No. of signs - 0" = sum(nsym == 0)/n() * 100,
    "No. of signs - 1" = sum(nsym == 1)/n() * 100,
    "No. of signs - 2" = sum(nsym == 2)/n() * 100,
    "No. of signs - 3" = sum(nsym == 3)/n() * 100,
    "No. of signs - 4+" = sum(nsym >= 4)/n() * 100,
    "History - Previous myocardial infarction" = sum(prevmi == 1, na.rm =T)/n() * 100,
    "History - Current anigma" = sum(angina == 1, na.rm =T)/n() * 100,
    "History - Diabetes" = sum(diabetes == 1)/n() * 100,
    "History - Hypertension" = sum(hyperten == 1, na.rm =T)/n() * 100,
    "Previous digoxin use" = sum(diguse == 1)/n() * 100,
    "Cause - Ischemic" = sum(chfetiol == 1, na.rm =T)/n() * 100,
    "Cause - Nonischemic" = sum(chfetiol != 1, na.rm =T)/n() * 100,
    "Cause - Nonischemic - Idiopathic" = sum(chfetiol == 4, na.rm =T)/n() * 100,
    "Cause - Nonischemic - Hypertensive" = sum(chfetiol == 2, na.rm =T)/n() * 100,
    "Cause - Nonischemic - Other" = sum(chfetiol %in% c(3, 5, 6), na.rm =T)/n() * 100,
    "Medications - Diuretics" = sum(diuretk == 1 | diuret == 1, na.rm =T)/n() * 100,
    "Medications - ACE inhibitors" = sum(aceinhib == 1)/n() * 100,
    "Medications - Nitrates" = sum(nitrates == 1)/n() * 100,
    "Medications - Other vasodilators" = sum(vasod == 1, na.rm =T)/n() * 100,
    "Dose - 0.125 mg" = sum(digdose == 0.125, na.rm =T)/n() * 100,
    "Dose - 0.250 mg" = sum(digdose == 0.250, na.rm =T)/n() * 100,
    "Dose - 0.375 mg" = sum(digdose == 0.375, na.rm =T)/n() * 100,
    "Dose - 0.500 mg" = sum(digdose == 0.500, na.rm =T)/n() * 100
  ) %>% round(1) %>% t()
colnames(tab1) <- c("Placebo", "Digoxin")
tab1[,c(2,1)] %>% 
  stargazer(header = F, summary = F, digits = 1)
```


```{r eval = F}
dig2 <- dig %>% 
  mutate(
    time = if_else(whfdays < deathday, whfdays, deathday),
    event = if_else((whf | death), 1, 0),
    ejf_25 = (ejf_per < 0.25),
    ejf_25_45 = (ejf_per > 0.25 & ejf_per < 0.45),
  )

surv_object <- Surv(time = dig2$time, event = dig2$event)
fit1 <- survfit(surv_object ~ trtmt, data = dig2)
# summary(fit1)
ggsurvplot(fit1, xlab = "Time", ylab = "Est. Survival Probability",
           ylim = c(0,1), conf.int = T, censor = F)

coxph(Surv(time, event) ~ ejf_25 + ejf_25_45, data = dig2) 
```

```{r}

tab4 <- function(condition = "T") {
  dig2 <- dig %>% 
    filter(!! rlang::parse_expr(condition))
  
  props <- dig2 %>% 
    group_by(trtmt) %>% 
    summarize(
      n_whf = sum(dwhf),
      n_total = n(),
      pct_whf = round(n_whf/n_total * 100, 1)
    )
  props2 <- props[c(2,1),] %>% 
    as.data.frame()
  rownames(props2) <- c("Digoxin", "Placebo")
  
  props_vec <- c(props2[1,2], props2[1,3], props2[1,4],
                 props2[2,2], props2[2,3], props2[2,4])
  
  test <- prop.test(x = props2$n_whf, n = props2$n_total,
            alternative = "two.sided", correct=F)
  
  absdif <- c((test$estimate[1] - test$estimate[2]) * 100, test$conf.int * 100) %>% 
    round(1)
  #rownames(absdif) <- c("Abs. Difference", "CI Low", "CI High")
  
  cox <- coxph(Surv(dwhfdays, dwhf) ~ trtmt, data = dig2) %>% summary()
  rr <- cox$conf.int[c(1,3,4)] %>% 
    round(2)
  #rownames(rr) <- c("Risk Ratio", "CI Low", "CI High")
  
  vec <- c(props_vec, absdif, rr) %>%
    as.data.frame() %>% 
    t()
  colnames(vec) <- c("N Digoxin", "N Digoxin Total", "Pct Digoxin", "N Placebo", 
                     "N Placebo Total", "Pct Placebo", "Abs. Difference", 
                     "CI Low", "CI High","Risk Ratio", "CI Low", "CI High")
  
  return(vec)
}

conditions <- c("ejf_per >= 25 & ejf_per <= 45", "ejf_per < 25", "diguse == 1", 
                "diguse == 0", "chfetiol == 1", "chfetiol != 1", 
                "chestx <= 0.55", "chestx > 0.55", "functcls %in% c(1,2)", 
                "functcls %in% c(3,4)", "T")
df <- tab4(conditions[1])
for (cond in conditions[-1]) {
  df <- rbind(df, tab4(cond))
}

rownames(df) <- c("Ejection fraction 0.25-0.45",
                  "Ejection fraction <0.25",
                  "Previous digoxin - Yes",
                  "Previous digoxin - No",
                  "Cause - Ischemic",
                  "Cause - Nonischemic",
                  "Cardiothoracic ratio <=0.55",
                  "Cardiothoracic ratio >0.55",
                  "NYHA - I or II",
                  "NYHA - III or IV",
                  "Overall Study Population")
```

\begin{landscape}
```{r outtab4, results = 'asis'}
rnames <- c("Ejection fraction 0.25-0.45",
                  "Ejection fraction <0.25",
                  "Previous digoxin - Yes",
                  "Previous digoxin - No",
                  "Cause - Ischemic",
                  "Cause - Nonischemic",
                  "Cardiothoracic ratio <=0.55",
                  "Cardiothoracic ratio >0.55",
                  "NYHA - I or II",
                  "NYHA - III or IV",
                  "Overall Study Population")
stargazer(df, header = F, summary = F, digits = 2, rownames = T, 
          font.size="tiny")
```
\end{landscape}

